# Generated by Django 2.2.5 on 2020-05-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='viewed',
            new_name='As_viewed',
        ),
    ]
