# Generated by Django 2.2.5 on 2020-05-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybasic_app', '0006_article_reviwer_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reviwer_list',
        ),
        migrations.AddField(
            model_name='article',
            name='reviwer_list',
            field=models.ManyToManyField(to='mybasic_app.Evaluateur'),
        ),
    ]
