# Generated by Django 2.2.5 on 2020-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybasic_app', '0008_auto_20200521_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reviwer_list',
        ),
        migrations.AddField(
            model_name='evaluateur',
            name='artcl_a_corrige',
            field=models.ManyToManyField(to='mybasic_app.Article'),
        ),
    ]
