# Generated by Django 2.2.5 on 2020-05-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybasic_app', '0009_auto_20200521_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluateur',
            name='artcl_a_corrige',
            field=models.ManyToManyField(default=None, to='mybasic_app.Article'),
        ),
    ]
