# Generated by Django 2.2.5 on 2020-06-02 08:55

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybasic_app', '0012_auto_20200522_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(null=True, upload_to='documents_Chercheur/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
