# Generated by Django 2.2.5 on 2020-06-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybasic_app', '0014_auto_20200602_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commite',
            old_name='sepiceilite',
            new_name='Name',
        ),
    ]
