# Generated by Django 2.2.5 on 2020-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybasic_app', '0015_auto_20200603_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluateur',
            name='count_pair_temporaire',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluateur',
            name='Code_Eval',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
